// app/layout.tsx  (RootLayout)
import "./globals.css"; // your global styles
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin", "latin-ext"], // <- gives ą ć ę ł ń ó ś ź ż
  weight: ["400", "600", "700"], // keep only the weights you need
  display: "swap",
  variable: "--font-poppins", // exposes a CSS variable
});

export const metadata = {
  title: "My site",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pl" className={poppins.variable}>
      {/* body can have more utility classes if you like */}
      <body>{children}</body>
    </html>
  );
}
